name: Release Commenter
description: Comment on PRs and Issues when a fix is released
branding:
  icon: message-square
  color: blue
inputs:
  GITHUB_TOKEN:
    description: |
      A GitHub personal access token with repo scope, such as
      secrets.GITHUB_TOKEN.
    required: true
  comment-template:
    description: |
      Text template for the comment string.
    required: false
    default: |
      Included in release {release_link}
  label-template:
    description: Add the given label. Multiple labels can be separated by commas.
runs:
  using: node12
  main: dst/index.js
