name: Release Commenter
description: Comment on PRs and Issues when a fix is released
branding:
  icon: message-square
  color: blue
inputs:
  GITHUB_TOKEN:
    description: |
      A GitHub personal access token with repo scope, such as
      secrets.GITHUB_TOKEN.
    required: true
  comment-template:
    description: |
      Text template for the comment string. `{release_link}` will be replaced
      with a markdown link to the release. Set to the empty string to disable
      commenting.
    required: false
    default: |
      Included in release {release_link}
runs:
  using: node12
  main: dst/index.js
