name: Release Commenter
description: Comment on PRs and Issues when a fix is released
branding:
  icon: message-square
  color: blue
inputs:
  GITHUB_TOKEN:
    description: |
      This should be a token with access to your repository scoped in as a secret, e.g. secrets.GITHUB_TOKEN
    required: true
  comment-template:
    description: |
      Text template for the comment string. `{release_link}` will be replaced with a markdown link to the release.
    required: false
    default: |
      Included in release {release_link}
runs:
  using: node12
  main: dst/index.js
