name: Dev workflow

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Tag
        uses: zwaldowski/semver-release-action@v1
        id: tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump: prerelease
          preid: alpha

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.version_tag }}
          release_name: ${{ steps.tag.outputs.version_tag }}
          prerelease: true
