name: Dev workflow

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Tag
        uses: zwaldowski/semver-release-action@v2
        id: tag
        with:
          github_token: ${{ secrets.RELEASE_GH_TOKEN }}
          bump: prerelease
          prefix: v
          preid: dev
